name: storymate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # GetX 라이브러리 추가
  flutter_svg: ^2.0.17 # svg 이미지 적용을 위한 라이브러리
  intl: ^0.20.2 # DateTime -> 문자열 변환을 위함
  flutter_dotenv: ^5.2.1
  kakao_flutter_sdk: ^1.9.6
  web_socket_channel: ^3.0.2
  package_info_plus: ^8.2.1
  dio: ^5.3.2
  shared_preferences: ^2.0.11
  http: ^1.0.0
  flutter_screenutil: ^5.9.3 # 반응형
  highlightable_text: ^0.0.1 # 하이라이트 기능
  in_app_purchase: ^3.2.1
  get_storage: ^2.1.1 # Get_Storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_white_bg.png" # 아이콘 파일 경로

flutter:
  uses-material-design: true
  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumGothic.ttf
  assets:
    - assets/
    - assets/books/
    - assets/kim_cheomji.png
    - assets/mermaid.png
    - assets/TheLittleGirl.png
    - assets/SimCheong.png
    - assets/mermaid2.png
    - assets/Dongbaekkkot.png
    - assets/mouse.png
    - assets/duck.png
    - assets/theBuckwheatFlower.png
    - assets/HongGildong.png
    - .env
